name: Deploy to GitHub Pages
on:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  mirror-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git push origin HEAD:gh-pages --force
